name: dart_pdf_renderer_workspace
publish_to: none

environment:
  sdk: ^3.12.1

workspace:
  - packages/*

dependency_overrides:
  pdf_cos:
    path: third_party/dart-pdf/packages/pdf_cos
  pdf_document:
    path: third_party/dart-pdf/packages/pdf_document
  pdf_graphics:
    path: third_party/dart-pdf/packages/pdf_graphics
